name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/1 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "18210427950@qq.com"
          git config --local user.name "yancie2015"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "AutoGreen!"
          git push
